### ISSUE TITLE
EHunkApplyException raised starting Node v2.1.0

### ISSUE THREAD

**Issue by zioju** [crynux-ai/crynux-node#283]
Starting the Node in Docker  returns the following error message :

2024-07-17 22:03:23 crynux_node  | Traceback (most recent call last):
2024-07-17 22:03:23 crynux_node  |   File "/app/worker/crynux_worker_process.py", line 241, in <module>
2024-07-17 22:03:23 crynux_node  |     apply_patch(patch_content)
2024-07-17 22:03:23 crynux_node  |   File "/app/worker/crynux_worker_process.py", line 53, in apply_patch
2024-07-17 22:03:23 crynux_node  |     new_contents = whatthepatch.apply_diff(diff, old_content)
2024-07-17 22:03:23 crynux_node  |   File "/app/worker/venv/lib/python3.10/site-packages/whatthepatch/apply.py", line 116, in apply_diff
2024-07-17 22:03:23 crynux_node  |     raise HunkApplyException(
2024-07-17 22:03:23 crynux_node  | whatthepatch.exceptions.HunkApplyException: context line 44, "        from gpt_task.prefetch import prefetch_models as gpt_prefetch_models" does not match "", in hunk #1

**Comment by zioju** [comment]
solved removing /config folder and restarting the container.
